put some error handling in package installation  fix typo

diff --git a/.github/workflows/build_html_from_rmd_files.yml b/.github/workflows/build_html_from_rmd_files.yml
--- a/.github/workflows/build_html_from_rmd_files.yml
+++ b/.github/workflows/build_html_from_rmd_files.yml
@@ -21,14 +21,29 @@ jobs:
         run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev
       - name: Download and install specific package versions
         run: |
-          wget -O desc_1.4.3.tar.gzt https://github.com/r-lib/desc/archive/refs/tags/v1.4.3.tar.gz
+          wget -O desc_1.4.3.tar.gz https://github.com/r-lib/desc/archive/refs/tags/v1.4.3.tar.gz
           wget -O brio_1.1.3.tar.gz https://github.com/r-lib/brio/archive/refs/tags/v1.1.3.tar.gz
           wget -O downlit_0.4.2.tar.gz https://github.com/r-lib/downlit/archive/refs/tags/v0.4.2.tar.gz
       - name: Install specific package versions
         run: |
-          R CMD INSTALL desc_1.4.3.tar.gz
-          R CMD INSTALL brio_1.1.3.tar.gz
-          R CMD INSTALL downlit_0.4.2.tar.gz
+          if [ -f "desc_1.4.3.tar.gz" ]; then
+            R CMD INSTALL desc_1.4.3.tar.gz
+          else
+            echo "desc_1.4.3.tar.gz not found"
+            exit 1
+          fi
+          if [ -f "brio_1.1.3.tar.gz" ]; then
+            R CMD INSTALL brio_1.1.3.tar.gz
+          else
+            echo "brio_1.1.3.tar.gz not found"
+            exit 1
+          fi
+          if [ -f "downlit_0.4.2.tar.gz" ]; then
+            R CMD INSTALL downlit_0.4.2.tar.gz
+          else
+            echo "downlit_0.4.2.tar.gz not found"
+            exit 1
+          fi
       - name: Install rmarkdown
         run: Rscript -e 'install.packages("rmarkdown", repos = "https://cloud.r-project.org")'
       - name: Render Book
